version: "3.8"

services:
  db:
    image: postgres:13
    container_name: Rescounts_Task_db
    environment:
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: Rescounts_Task_server
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myapp_user
      - DB_PASSWORD=password
      - DB_NAME=myapp
      - STRIPE_SECRET_KEY=your-YOUR_STRIPE_TEST_KEY
    ports:
      - "8080:8080"
    command: ["./server"]

volumes:
  db_data:
